steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg',
      'env=${_ENV}',
      '-t',
      'gcr.io/poltio-164412/poltio-ip',
      '.']
    # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/poltio-164412/poltio-ip']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'alpha',
      'run',
      'deploy',
      'poltio-ip-${_ENV}',
      '--image',
      'gcr.io/poltio-164412/poltio-ip',
      '--platform',
      'gke',
      '--cluster',
      'poltio-cluster-1',
      '--cluster-location',
      'europe-west1-b',
      '--min-instances',
      '${_MIN_I}']

images:
  - gcr.io/poltio-164412/poltio-ip
